### ISSUE TITLE
Song skipped with this error message

### ISSUE THREAD

**Issue by highsaffron** [minemidnight/oxyl#35]
`Error: No stream returned after extraction     at Player.play (/home/dbots/oxyl/src/bot/structures/player.js:92:23)     at <anonymous>`

This was the video that caused the error: https://www.youtube.com/watch?v=ra9YS85YzvE&list=PLUdZtU2Jvk4aeAkq1LoF9ZyWEKRhUqSkY&index=6

EDIT: three other links caused this issue
1. https://www.youtube.com/watch?v=ULaxICXLcCQ&list=PLUdZtU2Jvk4aeAkq1LoF9ZyWEKRhUqSkY&index=11
2. https://www.youtube.com/watch?v=_E8RGnJru28&list=PLUdZtU2Jvk4aeAkq1LoF9ZyWEKRhUqSkY&index=12
3. https://www.youtube.com/watch?v=TjYFe1tUG3E&list=PLUdZtU2Jvk4aeAkq1LoF9ZyWEKRhUqSkY&index=13

**Comment by minemidnight** [comment]
not a bot error, problem with ytdl
