### ISSUE TITLE
Error when using the google command

### ISSUE THREAD

**Issue by Jarvvski** [minemidnight/oxyl#41]
When a user tries the google command, it returns with the following response:

```
Error: Service Unavailable
    at Request.callback (/home/mine/oxyl/node_modules/superagent/lib/node/index.js:686:11)
    at IncomingMessage.<anonymous> (/home/mine/oxyl/node_modules/superagent/lib/node/index.js:868:18)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1057:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I'm not a big JS guy otherwise I'd have a look at it myself

**Comment by bjxke** [comment]
Yeah, this is due to google. Nothing wrong with the bot.

**Comment by Jarvvski** [comment]
@DoctorDarkMagic this is due to google?

I'm confused what you mean by that.

**Comment by bjxke** [comment]
It grabs data off Google, but the method minemidnight uses often gets blocked by Google. Just try again later and it should work.

**Comment by Jarvvski** [comment]
Sounds like it should get caught by the bot then, instead of just spitting out a stack trace

**Comment by bjxke** [comment]
Well, it does not happen all the time so no.

**Comment by Jarvvski** [comment]
I mean, using a simple try/catch is not that hard

it's better than spitting out errors to end-users

Edit: It also errors out every time I use the `google` command, afaik

**Comment by bjxke** [comment]
It shouldn't do all the time. minemidnight is working on the rewrite so it should be fixed in the rewrite when it's released.

**Comment by Jarvvski** [comment]
It's bad if you don't catch an error though

You should catch any potential errors

**Comment by bjxke** [comment]
Well that's the owners fault, not mine.

**Comment by minemidnight** [comment]
Being removed
